#output directory
output_dir: /path/to/out/dir

# tsv file with an absolute file path per line
file_list: /path/to/file/list.txt

# number of genomes per batch for saving pyrodigal files
pyrodigal_num_batches: 2000

# number of genomes per MMseqs2 batch
mmseqs2_num_batches: 200000

# MMseqs2 clustering parameters
mmseqs2_min_ID: 0.5
mmseqs2_min_cov: 0.5
mmseqs2_cov_mode: 0
mmseqs2_ID_mode: 0
mmseqs2_tmp_dir: /path/to/tmp/dir

